name: Continuous Integration and Deployment (CI/CD)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  

      - name: Install dependencies
        run: |
          cd src
          dotnet restore

      - name: Build the project
        run: |
          cd src
          dotnet build --configuration Release

      - name: Run tests
        run: |
          cd test
          dotnet test --configuration Release --no-build

  publish:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  

      - name: Authenticate with GitHub Packages
        run: |
          echo "PACKAGE_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Pack the project
        run: |
          cd src
          dotnet pack --configuration Release --output ./nupkgs

      - name: Publish package to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"