name: Continuous Integration and Deployment (CI/CD)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test $(find . -name '*Tests.csproj') --configuration Release --no-build

  publish:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
    
      - name: Generate dynamic version
        run: |
            VERSION="1.0.${{ github.run_number }}"
            echo "Generated version: $VERSION"
            find . -name '*.csproj' -exec sed -i 's|<Version>.*</Version>|<Version>'$VERSION'</Version>|' {} +
            cat $(find . -name '*.csproj')

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Publish package to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          --skip-duplicate